#!/bin/bash
# ============================================
# Monty GitHub Push Script
# Push completed projects to GitHub
# ============================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

# Parse arguments
PROJECT_DIR="$1"
PROJECT_NAME="$2"
CLEANUP="${3:-no}"  # Default: don't cleanup

# Validate inputs
if [ -z "$PROJECT_DIR" ] || [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}Usage: $0 <project_dir> <project_name> [cleanup]${NC}"
    echo -e "  cleanup: 'yes' to delete local files after push (default: 'no')"
    exit 1
fi

if [ ! -d "$PROJECT_DIR" ]; then
    echo -e "${RED}Error: Project directory not found: $PROJECT_DIR${NC}"
    exit 1
fi

# Check for GitHub CLI
if ! command -v gh &>/dev/null; then
    echo -e "${RED}Error: GitHub CLI not found${NC}"
    echo ""
    echo "Install with:"
    echo "  macOS: brew install gh"
    echo "  Linux: see https://github.com/cli/cli#installation"
    echo ""
    echo "Then authenticate: gh auth login"
    exit 1
fi

# Check GitHub auth status
if ! gh auth status &>/dev/null; then
    echo -e "${YELLOW}GitHub authentication required${NC}"
    echo "Please run: gh auth login"
    exit 1
fi

# Get current GitHub user
GITHUB_USER=$(gh api user --jq '.login')
if [ -z "$GITHUB_USER" ]; then
    echo -e "${RED}Error: Could not get GitHub username${NC}"
    exit 1
fi

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Pushing to GitHub${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
echo -e "Project: ${BOLD}$PROJECT_NAME${NC}"
echo -e "Directory: $PROJECT_DIR"
echo -e "GitHub User: $GITHUB_USER"
echo ""

# Create safe repository name
REPO_NAME=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')

# Check if repo already exists
if gh repo view "$GITHUB_USER/$REPO_NAME" &>/dev/null; then
    echo -e "${YELLOW}Repository already exists: $GITHUB_USER/$REPO_NAME${NC}"
    echo -n "Do you want to overwrite it? (y/N): "
    read -r CONFIRM
    if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
    echo "Deleting existing repository..."
    gh repo delete "$GITHUB_USER/$REPO_NAME" --yes
    sleep 2  # Give GitHub a moment to process deletion
fi

# Navigate to project directory
cd "$PROJECT_DIR"

# Initialize git if not already initialized
if [ ! -d ".git" ]; then
    echo "Initializing git repository..."
    git init
    git branch -M main
fi

# Create .gitignore if it doesn't exist
if [ ! -f ".gitignore" ]; then
    cat > .gitignore << 'EOF'
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv
.env
*.egg-info/
dist/
build/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# Docker
*.log
.docker/

# Database
*.db
*.sqlite
*.sqlite3

# Secrets
.env*
!.env.example
secrets/
credentials/
*.key
*.pem
*.crt
EOF
    echo "Created .gitignore"
fi

# Add all files and create initial commit if needed
if ! git diff --cached --quiet 2>/dev/null || ! git diff --quiet 2>/dev/null || [ -n "$(git ls-files --others --exclude-standard)" ]; then
    echo "Adding files to git..."
    git add -A

    # Create commit message
    COMMIT_MSG="Initial project setup for $PROJECT_NAME

Generated by Monty - Autonomous AI Development Agent
https://github.com/anthropics/claude-code"

    git commit -m "$COMMIT_MSG" || true
fi

# Create GitHub repository
echo ""
echo "Creating GitHub repository: $REPO_NAME"

DESCRIPTION="$PROJECT_NAME - Built with Monty AI"

# Create public repository
gh repo create "$REPO_NAME" \
    --public \
    --description "$DESCRIPTION" \
    --source=. \
    --remote=origin \
    --push \
    2>/dev/null || {
    # If create fails, try to set remote and push manually
    echo "Setting up remote manually..."
    git remote remove origin 2>/dev/null || true
    git remote add origin "https://github.com/$GITHUB_USER/$REPO_NAME.git"
    git push -u origin main --force
}

# Get the repository URL
REPO_URL="https://github.com/$GITHUB_USER/$REPO_NAME"

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Successfully pushed to GitHub!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Repository: ${CYAN}$REPO_URL${NC}"
echo -e "Clone with: ${CYAN}git clone $REPO_URL${NC}"
echo ""

# Open in browser
echo -n "Open repository in browser? (Y/n): "
read -r OPEN_BROWSER
if [ "$OPEN_BROWSER" != "n" ] && [ "$OPEN_BROWSER" != "N" ]; then
    gh repo view --web "$GITHUB_USER/$REPO_NAME"
fi

# Cleanup if requested
if [ "$CLEANUP" = "yes" ]; then
    echo ""
    echo -e "${YELLOW}Cleaning up local files...${NC}"
    cd ..
    rm -rf "$PROJECT_DIR"
    echo -e "${GREEN}Local files deleted.${NC}"
    echo -e "Project is now only on GitHub: $REPO_URL"
else
    echo ""
    echo -e "${CYAN}Local files preserved at: $PROJECT_DIR${NC}"
    echo "To delete them later, run: rm -rf \"$PROJECT_DIR\""
fi

echo ""
echo -e "${MAGENTA}\"Excellent...\" - Monty${NC}"